#!/bin/sh
sed 's/	/        /g' $* | awk '
BEGIN {
	N = 40
	for (i = 1; i <= N; i++)
		blanks = blanks " "
}

{
	if ((n = length($0)) <= N)
		print
	else {
		i = 1
		while (n > N) {
			ln = substr($0,i,N-1)
			#printf "N: %s\\n", N
			for (m = length(ln); m >= 1; m--) {
				if (substr(ln, m, 1) == " " || substr(ln, m, 1) == "\t")
					break;
			}
			if (m > 1) {
				ln = substr($0,i,m)
				printf "%s\n", ln
				i += length(ln)
				n -= length(ln);
			} else {
				i += N-1;
				n -= N-1;
				printf "%s-\n", ln
			}
		}
		printf "%s%s\n", substr(blanks,1,N-n), substr($0,i)
	}
}
'

