#!/bin/sh
t=${1-60}

while :
do
	news="$(who | cut -d' ' -f1)"
	for new in $news; do
			if ! echo $olds | grep $new >/dev/null; then
				echo "in: $new"
			fi
	done

	for old in $olds; do
		if ! echo $news | grep $old >/dev/null; then
			echo "out: $old"
		fi
	done

	olds="$news"
	sleep 1
done
