#!/bin/sh

# This seems to be the only way to write bundle given the facilities in the book
for i in $*
do
	# Assumes bundle is in PATH
	(cd "$i" && bundle *) || {
			echo "echo $1 1>&2"
			echo "cat >$i << 'End of $i'"
			ls -l $i
			cat $i
			echo "End of $i"
		}
done
