#!/bin/sh

VERSION=0
while test "$1" != ""
do
	case "$1" in
		-i)	INPUT=$2; shift ;;
		-o)	OUTPUT=$2; shift ;;
		-[0-9])	VERSION=$1 ;;
		-*)	echo "$0: Unkonwn argument $i" 1>&2 ;;
		*)
			case "$OUTPUT" in
				"") OUTPUT=$1 ;;
				*) INPUT=$1.H ;;
			esac


	esac
	shift
done
OUTPUT=${OUTPUT?"Usage: $0 [-o outfile] [-i file.H] file"}
INPUT=${INPUT-$OUTPUT.H}
test -r $INPUT || { echo "$0: no file $INPUT" 1>&2; exit 1; }
trap 'rm -f /tmp/get.[ab]$$; exit 1' 1 2 15
sed <$INPUT -n '
	1,/^@@@/w /tmp/get.a'$$'
	/^@@@/,$w /tmp/get.b'$$

awk </tmp/get.b$$ '
	/^@@@/ { count++ }
	!/^@@@/ && count > 0 && count <= - '$VERSION'
	END { print "$d"; print "w", "'$OUTPUT'" }
' | ed - /tmp/get.a$$
rm -f /tmp/get.[ab]$$
