#!/bin/sh
HOME=.
cd .
IFS='
'

for_cmd='echo \($i\): "$3" "$5" "$6" "$7"; cat "$i"'
end_cmd='touch "$HOME/.news_time"'

case "$1" in
	-n)
		for_cmd='echo \("$i"\): "$3" "$5" "$6" "$7"';
		end_cmd=''
;;
esac

for i in `ls -t * $HOME/.news_time 2>&1`
do
	IFS=' '
	case $i in
		*' not found')  ;;
		*/.news_time)  break ;;
		*)	set X`ls -l "$i"`
			eval $for_cmd;;
	esac
done

eval $end_cmd
