#!/bin/sh

case $# in
	0|1|2) echo "Usage: $0 str1 str2 files" 1>&2
		exit 1
esac

case $1 in
	-v) vflag="w /dev/fd/0" shift;;
esac

left="$1"; shift
right="$1"; shift

for i
do
	overwrite $i sed "s@$left@$right@g$vflag" $i
done
